import type { Metadata } from "next";
import "./ui/globals.css";
import Header from "./ui/layout/header";
import Footer from "./ui/layout/footer";
import { paragraph } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={paragraph.className}>
        <Header />
        <main className="min-h-[50vh] md:min-h-[80vh] max-w-[1500px] mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
